# Site settings
title: Zheey's Blog
SEOTitle: Zheey's Blog
header-img: img/home-bg-desk.jpg
email: zhezheey@yeah.net
description: "A Simple Personal Blog."
keyword: "zheey, Zheey's Blog, CS"
url: "http://zhezheey.github.io" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/zhezheey/zhezheey.github.io.git" # your code repository

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "CS, BUPT"
sidebar-avatar: /img/about-zheey.png # use absolute URL, seeing it's used in both `/` and `/about/`

# SNS settings
RSS: false
# weibo_username:     zhezheey
# zhihu_username:     zhezheey
github_username:    zhezheey
# facebook_username:  zhezheey
# jianshu_username:   zhezheey
# twitter_username:   zhezheey

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM # use Github Flavored Markdown (important)

# Review system
# Disqus（https://disqus.com/）
# disqus_username: zhezheey

# Gitalk
gitalk:
  enable: false    # Gitalk or not
  clientID: fd7fe9d2680c529a0c42
  clientSecret: f30018c52c18fd1f8308f1d3dba0299802f119b2
  repo: zhezheey.github.io
  owner: zhezheey
  admin: zhezheey
  distractionFreeMode: true

# Statistics

# Analytics settings
# Baidu Analytics
ba_track_id: 241eaf1576e592a3f1077c62d60e4138

# Google Analytics
ga_track_id: 'UA-129103079-1' # Format: UA-xxxxxx-xx
ga_domain: zheey.com # Default: auto

# Featured Tags
featured-tags: true                     # Home tag or not
featured-condition-size: 1              # If the number of same tags is greater than this number, it will appear on the home page.

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Friends
# friends: [
#     {
#         title: "",
#         href: ""
#     }
# ]
